name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Build egg
      run: |
        python setup.py bdist_egg

    - uses: actions/upload-artifact@v4
      with:
        name: pieces
        path: |
          dist/*.egg

    - uses: ncipollo/release-action@v1
      with:
        commit: "${{github.sha}}"
        tag: "${{github.sha}}"
        artifacts: "dist/*.egg"
#        bodyFile: "readme.md"
        body: "Automatic release"
